export const GET_FILM_LIST = "GET_FILM_LIST";
export const GET_FILM_LIST_SUCCESS= 'GET_FILM_LIST_SUCCESS';
export const GET_FILM_LIST_FAILURE= 'GET_FILM_LIST_FAILURE';

export const GET_FILM_DETAILS = "GET_FILM_DETAILS";
export const GET_FILM_DETAILS_SUCCESS= 'GET_FILM_DETAILS_SUCCESS';
export const GET_FILM_DETAILS_FAILURE= 'GET_FILM_DETAILS_FAILURE';
